/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#2a2a2c",
        "on-tertiary-fixed": "#1b1b1e",
        "on-secondary-container": "#bcbbc5",
        "primary-fixed": "#e2e2e3",
        "on-primary-fixed": "#1a1c1d",
        "surface-dim": "#131315",
        "on-surface": "#e5e1e4",
        "on-tertiary-container": "#656467",
        "secondary-container": "#4a4b53",
        "on-background": "#e5e1e4",
        "on-secondary": "#2f3038",
        "surface-container-lowest": "#0e0e10",
        "surface": "#131315",
        "surface-bright": "#39393b",
        "surface-container-highest": "#353437",
        "on-primary-container": "#636466",
        "surface-container": "#201f22",
        "tertiary-container": "#e4e1e5",
        "tertiary-fixed-dim": "#c8c6c9",
        "on-primary": "#2f3132",
        "error": "#ffb4ab",
        "background": "#131315",
        "primary": "#ffffff",
        "on-surface-variant": "#c4c7c9",
        "outline-variant": "#444749",
        "surface-variant": "#353437",
        "inverse-on-surface": "#313032",
        "secondary-fixed": "#e3e1ec",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "primary-container": "#e2e2e3",
        "on-secondary-fixed": "#1a1b22",
        "secondary": "#c6c5cf",
        "on-tertiary-fixed-variant": "#47464a",
        "surface-container-low": "#1c1b1d",
        "inverse-primary": "#5d5e60",
        "primary-fixed-dim": "#c6c6c7",
        "on-secondary-fixed-variant": "#46464e",
        "inverse-surface": "#e5e1e4",
        "error-container": "#93000a",
        "outline": "#8e9193",
        "secondary-fixed-dim": "#c6c5cf",
        "tertiary-fixed": "#e4e1e5",
        "on-primary-fixed-variant": "#454748",
        "tertiary": "#ffffff",
        "surface-tint": "#c6c6c7",
        "on-tertiary": "#303033"
      },
      fontFamily: {
        mono: ["JetBrains Mono", "monospace"],
        sans: ["Geist", "sans-serif"]
      }
    },
  },
  plugins: [],
}
